# Generated by Django 4.1.4 on 2023-06-22 13:53

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwtuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to=users.models.upload_to),
        ),
    ]
